name: pipeline-checker
on: [workflow_dispatch, push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install --legacy-peer-deps

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install --legacy-peer-deps

      - name: Run HTMLHint
        id: htmlhint
        run: npx htmlhint "**/*.html" --ignore "coverage/**"

      - name: Run Stylelint
        id: stylelint
        run: npx stylelint '**/*.css' --ignore-pattern "coverage/**"

      - name: ESLint Backend
        working-directory: ./backend
        run: npx eslint "**/*.{js,ts}" --ignore-pattern "coverage/**"

      - name: ESLint Frontend
        working-directory: ./frontend
        run: npx eslint "**/*.{js,ts,jsx,tsx}" --ignore-pattern "coverage/**"

      - name: Run ESLint (root)
        id: eslint
        run: npx eslint "**/*.{js,ts,jsx,tsx}" --ignore-pattern "coverage/**"

      - name: Run Jest tests backend
        working-directory: ./backend
        id: tests
        run: npx jest --coverage

      - name: Run npm audit
        id: npm-audit
        run: npm audit --audit-level=low

      - name: Build Next.js frontend
        working-directory: ./frontend
        id: build
        run: npm run build

      - name: Upload coverage folder as artifact
        if: steps.tests.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-artifact
          path: coverage/
