name: pipeline-checker
on: [workflow_dispatch, push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install root dev tools
        run: npm install

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Build Backend
        id: backend-build
        working-directory: ./backend
        run: npx nest build

      - name: ESLint Backend
        id: backend-eslint
        working-directory: ./backend
        run: npx eslint . --ext .ts

      - name: Mocha + NYC Backend
        id: backend-test
        working-directory: ./backend
        continue-on-error: true
        run: npm test

      - name: Run npm audit
        id: npm-audit
        run: npm audit --audit-level=high

      - name: Upload backend coverage folder as artifact
        if: ${{ steps.backend-test.conclusion == 'success' }}
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage/

      - name: Deploy Backend to Railway
        if: ${{ steps.backend-build.conclusion == 'success' && steps.backend-eslint.conclusion == 'success' && steps.backend-test.conclusion == 'success' && steps.npm-audit.conclusion == 'success' }}
        uses: bervProject/railway-deploy@main
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        with:
          service: "b1898c40-417b-41e9-ae8a-9096d4ded847"
