name: pipeline-checker
on: [workflow_dispatch, push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install --save-dev htmlhint stylelint-config-standard stylelint eslint@8 jest @types/jest ts-jest vite eslint-plugin-jest

      - name: Fix permissions for htmlhint
        run: chmod +x ./node_modules/.bin/htmlhint

      - name: Run HTMLHint
        id: htmlhint
        run: npx htmlhint "**/*.html" --ignore "coverage/**"
        continue-on-error: true

      - name: Fix permissions for stylelint
        run: chmod +x ./node_modules/.bin/stylelint

      - name: Run Stylelint
        id: stylelint
        run: npx stylelint '**/*.css' --ignore-pattern "coverage/**"
        continue-on-error: true

      - name: Fix permissions for ESLint
        run: chmod +x ./node_modules/.bin/eslint

      - name: Run ESLint
        id: eslint
        run: npx eslint "**/*.{js,ts}" --ignore-pattern "coverage/**"
        continue-on-error: true

      - name: Fix permissions for Jest
        run: chmod +x ./node_modules/.bin/jest

      - name: Run Jest
        id: tests
        run: npx jest --coverage
        continue-on-error: true

      - name: Run npm audit
        id: npm-audit
        run: npm audit --audit-level=low
        continue-on-error: true

      - name: Fix permissions for Vite
        run: chmod +x ./node_modules/.bin/vite

      - name: Run Vite Build
        id: vite
        run: npx vite build --mode production
        continue-on-error: true

      - name: Upload coverage folder as artifact
        if: steps.tests.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-artifact
          path: coverage/

      - name: Upload dist folder as artifact
        if: steps.vite.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: dist/

      - name: Vite Build passed?
        if: steps.vite.outcome == 'success'
        run: echo "Build completed successfully!"

      - name: Vite Build failed?
        if: steps.vite.outcome == 'failure'
        run: echo "Build failed, please check the errors!"

      - name: Jest passed?
        if: steps.tests.outcome == 'success'
        run: echo "Tests completed successfully!"

      - name: Jest failed?
        if: steps.tests.outcome == 'failure'
        run: echo "Tests failed, please check the errors!"

      - name: NPM Audit passed?
        if: steps.npm-audit.outcome == 'success'
        run: echo "No security issues found!"

      - name: NPM Audit failed?
        if: steps.npm-audit.outcome == 'failure'
        run: echo "Security issues found, please review npm audit output!"

      - name: HTMLHint passed?
        if: steps.htmlhint.outcome == 'success'
        run: echo "HTMLHint completed successfully, no errors found!"

      - name: HTMLHint failed?
        if: steps.htmlhint.outcome == 'failure'
        run: echo "HTMLHint failed, please check the errors!"

      - name: Stylelint passed?
        if: steps.stylelint.outcome == 'success'
        run: echo "Stylelint completed successfully, no errors found!"

      - name: Stylelint failed?
        if: steps.stylelint.outcome == 'failure'
        run: echo "Stylelint failed, please check the errors!"

      - name: ESLint passed?
        if: steps.eslint.outcome == 'success'
        run: echo "ESLint completed successfully, no errors found!"

      - name: ESLint failed?
        if: steps.eslint.outcome == 'failure'
        run: echo "ESLint found issues. Please fix them!"
